# Sử dụng Python 3.9
FROM python:3.9

# Thư mục làm việc
WORKDIR /app

# Copy requirements trước để cache
COPY requirements.txt ./

# Cài thư viện
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

# Mở cổng 5000
EXPOSE 5000

# Chạy app
CMD ["python", "app.py"]