# Sử dụng Nginx mới nhất
FROM nginx:latest

# Xóa file mặc định của nginx (tuỳ chọn)
RUN rm -rf /usr/share/nginx/html/*

# Copy file HTML vào thư mục nginx
COPY index.html /usr/share/nginx/html/

# Mở cổng 80
EXPOSE 80